develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35749:35729"
  environment:
    CT_URL: http://mymachine:9000 
    LOCAL_URL: http://mymachine:5000
    API_VERSION: v1
    CT_TOKEN: null
    CT_REGISTER_MODE: auto
  command: develop
  volumes:
    - ./app:/opt/query/app
